### ISSUE TITLE
Add method tabs to the perform a vector search page

### ISSUE THREAD

**Issue by kurtenj** [riptano/docs-ui#127]
Similar to the [**Load your data**](https://docs.datastax.com/en/astra/astra-db-vector/databases/load-data.html) page, we need to add tabs for **Astra Portal,** **Python**, **TypeScript**, and **Java** to the applicable sections of the [**Perform a vector search**](https://docs.datastax.com/en/astra/astra-db-vector/databases/vector-search.html) page.

<img width="862" alt="image" src="https://github.com/riptano/docs-ui/assets/6809612/c32e5476-f41d-41c8-9a62-c78069ee1cd8">

**Comment by eric-schneider** [comment]
The [Perform a vector search](https://docs.datastax.com/en/astra/astra-db-vector/databases/vector-search.html) page now has tabs for Astra Portal, Python, TypeScript, and Java 🤗
