### ISSUE TITLE
Add component title to left nav

### ISSUE THREAD

**Issue by eric-schneider** [riptano/docs-ui#134]
We don't provide users with an easy way to identify which component they're currently viewing. This is a big problem for wayfinding (especially for users arriving from Google search), and will continue to be a problem even after we introduce the global nav.

A good first step would be to add the component title to the top of the left nav. It should probably also be a link to the component start page (same as the breadcrumb). If the component has a version switcher, the title should sit adjacent to the version dropdown toggle.

NOTE: we should make sure to test long component titles to ensure that long titles wrap appropriately.

![image (9)](https://github.com/riptano/docs-ui/assets/37347760/386c504d-d00d-4aa2-b67f-6055d99243b3)

**Comment by eric-schneider** [comment]
@colegoldsmith I noticed that the version switcher got moved [above the component title](https://docs.datastax.com/en/dse/6.8/getting-started/get-started-dse.html) in the left nav. I thought it was supposed to be next to the component title (like in the screenshot above), but maybe there was a decision to reverse course that I wasn’t aware of?

**Comment by colegoldsmith** [comment]
Resolved with https://github.com/riptano/docs-ui/pull/159
