### ISSUE TITLE
Create diagrams to illustrate the client class hierarchy

### ISSUE THREAD

**Issue by skedwards88** [riptano/docs-ui#170]
Part of https://datastax.jira.com/browse/DOC-4752, following [this discussion](https://datastax.slack.com/archives/C07TJQCKCHG/p1729871345225419).

@kurtenj the technical diagrams are [here](https://docs.google.com/presentation/d/1B1aOk2mlH3fklY7Ylvsw1pHU1eA9E9173kuDF1zAe2E/edit#slide=id.g3124645e667_1_0). There is one diagram for each of the 3 clients; however, the Python and Java diagrams are identical. The TypeScript diagram only differs by a few class names.

Please let me know if you have any questions or need more information!

**Comment by kurtenj** [comment]
Thanks, @skedwards88! Attaching a sheet for these in both light and dark mode. Take a look and let me know if I captured all the details correctly. If they look good I'll prep individual SVG exports without a backgrounds.

![image](https://github.com/user-attachments/assets/1e13fb95-e968-4e2d-a9eb-ea95dda73ae5)
![image](https://github.com/user-attachments/assets/0c6dfd98-0f17-45ed-a34e-3b1a9124af9c)

**Comment by skedwards88** [comment]
Thanks @kurtenj ! Those look good to me.

**Comment by kurtenj** [comment]
> Thanks @kurtenj ! Those look good to me.

Awesome, individual SVGs attached here. Let me know once you test these to make sure that the colors are working correctly across both light and dark modes.

![java](https://github.com/user-attachments/assets/13a311f7-38a4-43c8-91a4-893b9a6de69b)
![python](https://github.com/user-attachments/assets/d978b843-ba38-44f8-bbdb-e15779578bbc)
![typescript](https://github.com/user-attachments/assets/caf3cb7b-fd27-49c7-a9f2-9e3fb212dd46)
