### ISSUE TITLE
OpenAI icon to left of topic title is white in light mode; ok in dark mode

### ISSUE THREAD

**Issue by johnsmartco** [riptano/docs-ui#62]
Hi.  When viewed in light-mode vector docs, the 20x20px icon to the left of the topic's title looks like a white square. Compare with dark mode.

<img width="1116" alt="Screenshot 2024-01-12 at 8 28 56 AM" src="https://github.com/riptano/docs-ui/assets/4041525/32219daf-93a5-4932-ad9b-ebe609a9ce79">

<img width="412" alt="Screenshot 2024-01-12 at 8 34 52 AM" src="https://github.com/riptano/docs-ui/assets/4041525/e10f91fb-f2f2-457f-91d1-900703713b50">

**Comment by johnsmartco** [comment]
cc: @colegoldsmith , @eric-schneider

**Comment by eric-schneider** [comment]
FYI, this isn't actually an issue with the UI per se, rather it requires a modification to the SVG so that it responds properly to light and dark mode. Cole just taught me how to do this, so I'll fix it in my next astra-vector-docs PR. I'll close this issue once it's fixed.

**Comment by djsauble** [comment]
@colegoldsmith's got a targeted fix for this here: https://github.com/riptano/astra-vector-docs/pull/200

**Comment by colegoldsmith** [comment]
Thanks @djsauble. Yep I've merged that in so this issue is resolved!
