### ISSUE TITLE
Right nav doesn't take the full height of the browser window

### ISSUE THREAD

**Issue by djsauble** [riptano/docs-ui#65]
![Screenshot 2024-01-16 at 9 25 23 AM](https://github.com/riptano/docs-ui/assets/186715/7d68b08e-f56b-4810-a2c9-9503ee23824c)

**Comment by colegoldsmith** [comment]
@djsauble I set the height that way to make room for the footer scrolling into view at the bottom of the page. If the ToC is full browser height it jumps up when the footer is visible. It's not the worst thing ever but it is a tradeoff with how the sticky element is stacked above a relative element. 

@kurtenj Would we want to prioritize giving the ToC more height even though it would jump up a little when scrolling to the bottom?

**Comment by djsauble** [comment]
I'd like to see what that transition looks like, but it sounds like a reasonable tradeoff to me.
