### ISSUE TITLE
Expand/collapse functionality for sub-headings in the left nav

### ISSUE THREAD

**Issue by eric-schneider** [riptano/docs-ui#66]
Headings in the left nav have expand/collapse functionality and default to collapsed state on page load. _Sub-headings should behave the same way_. However, currently, you can't expand/collapse sub-headings at all, and they default to open.

For example, see the sub-headings in the [**Databases**](https://fantastic-adventure-593lpwy.pages.github.io/main/astra-db-vector/databases/database-overview.html) section:

![Screen Shot 2024-01-16 at 7 02 35 PM](https://github.com/riptano/docs-ui/assets/37347760/34d13a47-53a3-417a-83f0-c73ad335f9dc)

**Comment by colegoldsmith** [comment]
Closed by https://github.com/riptano/docs-ui/pull/69
