### ISSUE TITLE
DataStax Docs banner image should link to actual docs homepage

### ISSUE THREAD

**Issue by eric-schneider** [riptano/docs-ui#71]
The DataStax Docs banner image should link to actual docs homepage: https://docs.datastax.com/en/home/docs/index.html

Currently, it links to the Serverless/Vector landing page: https://docs.datastax.com/en/astra/astra-db-vector/index.html

<img width="742" alt="image" src="https://github.com/riptano/docs-ui/assets/37347760/b48367ab-4de8-4460-98b7-73909ca1e053">

**Comment by colegoldsmith** [comment]
Will be closed by https://github.com/riptano/datastax-docs-site/pull/75
