### ISSUE TITLE
Nav collapse labels not clickable on mobile

### ISSUE THREAD

**Issue by colegoldsmith** [riptano/docs-ui#74]
unable to expand any of the parent sections for the nav on mobile. I tried multiple browsers.

![slackscreenshot](https://github.com/riptano/docs-ui/assets/5661374/e82a5010-e4d1-4ae1-b79e-007f897c690e)

**Comment by gopalchobey9** [comment]
@colegoldsmith  can u give a demo video of explaining the same

**Comment by colegoldsmith** [comment]
@gopalchobey9 I have a fix for this already in flight
