### ISSUE TITLE
Improve tab title wrapping

### ISSUE THREAD

**Issue by eric-schneider** [riptano/docs-ui#78]
For [tabsets](https://riptano.github.io/docs-ui/main/asciidoc/tabsets.html), the tab titles should have a more elegant text wrapping solution that allows tab titles to automatically scale appropriately across different width constraints.

We should probably set a minimum and maximum tab title width that looks good, and then allow for wrapping to a second line when the width is constrained. Not sure if we should allow wrapping to a third line, but we should set a maximum number of lines to wrap, after which the title overflows into ellipses (or something along those lines).

**Comment by eric-schneider** [comment]
Examples of tab overflow styles: https://mui.com/material-ui/react-tabs/#wrapped-labels

**Comment by gopalchobey9** [comment]
can you explain more...
