### ISSUE TITLE
Disable automatic external link styling when link is an image

### ISSUE THREAD

**Issue by eric-schneider** [riptano/docs-ui#83]
**NOTE**: This issue should probably be worked on in conjunction with https://github.com/riptano/docs-ui/issues/120.

In AsciiDoc, you can [add links to images](https://docs.asciidoctor.org/asciidoc/latest/macros/image-link/). However, when the link is an external link, the automatic external link styling implemented in [Automatic External Links](https://3.basecamp.com/5214332/buckets/27604022/card_tables/cards/6682958110) applies a box arrow icon to the image. This is undesirable, and we should update the CSS to ignore external links when they're a part of an image.

![image](https://github.com/riptano/docs-ui/assets/37347760/345aad6f-884e-433e-a3a9-7df6035cc70d)

**Comment by gopalchobey9** [comment]
@eric-schneider please provide the file name to be updated

**Comment by eric-schneider** [comment]
This was resolved in https://github.com/riptano/docs-ui/pull/171.
